#ifndef __IO_EXPANDER_ADDR_H_
#define __IO_EXPANDER_ADDR_H_


#define IO_EXPANDER_INT_PIN	17
#define IO_EXPANDER_INT_SCL	27
#define IO_EXPANDER_INT_SDA	26

#define INPUT_PORT_REGISTER 0X00
#define INPUT_INTERRUPT_MASK 0X45


#endif
